### ISSUE TITLE
Nextcloud automatic setup doesn't work

### ISSUE THREAD

**Issue by bretton** [bretton/minio-sampler#1]
Nextcloud automatic setup once logged into `minio1` doesn't work:

```
root@minio1:~ # ./preparenextcloud.sh 
MySQL username and/or password not valid
 -> You need to enter details of an existing account.
Trace: #0 /usr/local/www/nextcloud/lib/private/Setup.php(354): OC\Setup\MySQL->setupDatabase()
#1 /usr/local/www/nextcloud/core/Command/Maintenance/Install.php(108): OC\Setup->install()
#2 /usr/local/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute()
#3 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#4 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /usr/local/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#7 /usr/local/www/nextcloud/console.php(100): OC\Console\Application->run()
#8 /usr/local/www/nextcloud/occ(11): require_once('...')
#9 {main}

Previous: Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'nextcloud'@'10.200.1.15' (using password: YES)
Trace: #0 /usr/local/www/nextcloud/lib/private/Setup/MySQL.php(64): OC\DB\Connection->connect()
#1 /usr/local/www/nextcloud/lib/private/Setup.php(354): OC\Setup\MySQL->setupDatabase()
#2 /usr/local/www/nextcloud/core/Command/Maintenance/Install.php(108): OC\Setup->install()
#3 /usr/local/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute()
#4 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#5 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#6 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#7 /usr/local/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#8 /usr/local/www/nextcloud/console.php(100): OC\Console\Application->run()
#9 /usr/local/www/nextcloud/occ(11): require_once('...')
#10 {main}
```

It might be due to the nginx stream proxy for nginx or some other issue to do with networking.

**Comment by bretton** [comment]
This issue persists with latest version. I couldn't get automatic nextcloud setup working when using pf, or nginx as reverse proxy, or haproxy, however connecting to mysql works fine from within the nextcloud image, and it goes via haproxy. But it doesn't work with nextcloud setup, same error as above.

Should work on normal servers, just an issue in the vagrant/virtualbox setup.
